Upgrade to @react-native-async-storage/async-storage
awslabs/aws-mobile-appsync-sdk-js pull request #673
Opened 2021-09-21 18:45 UTC by jamesaucode

*Issue #, if available:*
#654 

*Description of changes:*
Upgrade from `@react-native-community/async-storage` to `@react-native-async-storage/async-storage`

Also upgrading `@redux-offline/redux-offline` to `2.6.0-native.1` as the old version depends on `@react-native-community/async-storage`

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-09-23 17:10 UTC, iartemiev requested changes

2021-09-23 17:10 UTC, iartemiev commented on packages/aws-appsync/package.json
>    }
Let's remove these `peerDependencies` altogether. See https://github.com/awslabs/aws-mobile-appsync-sdk-js/pull/675 for additional info.

2021-09-23 18:07 UTC, iartemiev approved these changes
LGTM 👍🏻

2021-09-23 18:10 UTC, merged

2021-09-24 15:23 UTC, andidev commented
This is really nice to hear its merged! When can we expect a release?

2021-09-24 17:00 UTC, iartemiev commented
Hey @andidev, we just released the change this morning in `aws-appsync@4.1.2`